arduino/arduino-lint-action

.github/workflows/check-toc.yml
README.md

On every push or pull request that affects the repository's README.md, use [markdown-toc](https://github.com/jonschlinkert/markdown-toc) to check whether the table of contents matches the content.

Add CI workflow to check for missed updates to readme ToC

---

.github/CONTRIBUTING.md
README.md

A few parts of the documentation content had become outdated since the time they were written. This brings them up to date.

Make some updates to documentation content

---

.github/dependabot.yml

Dependabot will periodically check all dependencies of the project. If any are found to be outdated, it will submit a pull request to update them:
- GitHub Actions actions
- npm packages

Configure Dependabot to check for outdated dependencies

---

.github/workflows/test.yml

[The `actions/setup-node` GitHub Actions action](https://github.com/actions/setup-node) is used in the "test" workflow to setup a specific version range of Node.js for use in the GitHub Actions runner.
The 2.x.x major version series of the action is now well into production status and the 1.x.x series is no longer under active development.
The use of the `v2` major version ref will cause the workflow to use a stable version of the action, while also benefiting from ongoing development to the action up until such time as a new major release of an action is made. At that time we would need to evaluate whether any changes to the workflow are required by the breaking change that triggered the major release before manually updating the major ref (e.g., uses: `actions/setup-node@v3`).
--- …

Bump `actions/setup-node` to v2

---

.github/CONTRIBUTING.md
.github/workflows/check-packaging-ncc-typescript-npm.yml
.github/workflows/integration.yml
README.md
dist/index.js

The previous development policy was to only repackage on each release. This prevented contributors from doing casual beta
testing by simply referencing the action as `arduino/arduino-lint-action@main` in a workflow.
This policy change is implemented via:
- Update development and release workflow documentation.
- Add a CI workflow to check for forgotten packaging.
- Repackage the current code.
- Adjust the integration testing workflow to account for new policy.
---
This aligns the development policy of this project with that of the `arduino/setup-task` action, which has successfully used continuous packaging for some time now (https://github.com/arduino/setup-task/pull/16).

Change development policy to continuous packaging

---

.github/workflows/check-npm.yml
README.md
package-lock.json

On every push and pull request that affects relevant files, and periodically:
- Validate [package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json) against [its JSON schema](https://json.schemastore.org/package.json).
- Check for forgotten [package-lock.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json) syncs.

Add CI workflow to check for problems with npm configuration files

---

.github/workflows/check-tsconfig.yml
README.md

On every push or pull request that affects the repository's [TypeScript configuration files](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), and periodically, validate them
against [their JSON schema](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#schema).

Add CI workflow to validate tsconfig.json files

---

.github/CONTRIBUTING.md
.github/workflows/check-npm.yml
.github/workflows/check-packaging-ncc-typescript-npm.yml
.github/workflows/test.yml
package-lock.json
package.json

The previous 10.x version is EOL. 16.x is [the newest version in LTS status](https://nodejs.org/en/about/releases/). LTS seems the most appropriate choice for the needs of this project.

Update Node.js version used for development and CI to 16

---

.github/workflows/integration.yml

Now that the development policy is to continuously package the project (https://github.com/arduino/arduino-lint-action/commit/f365dbdebe6a40389b78fff176dacaad3ede742f), and this policy is enforced by [a CI workflow](https://github.com/arduino/arduino-lint-action/blob/main/.github/workflows/check-packaging-ncc-typescript-npm.yml),
The action will always be pre-built, so building it again during the integration test workflow runs is pointless.
One of the build steps was removed from the workflow at the time the development policy was changed (https://github.com/arduino/arduino-lint-action/commit/01b5627902760a0d15893d4126e331137c258169), but the build steps in the other two jobs were missed at that time.

Remove unnecessary build steps from integration test workflow

---

.github/workflows/check-packaging-ncc-typescript-npm.yml

The [`on.*.paths` keys of GitHub workflows](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths) can be used to avoid unnecessary or unwanted workflow runs. This is done by
defining specific paths containing files relevant to the workflow's purpose. The workflow will only run when the trigger
event modifies a file matching the paths.
The "Check Packaging" workflow was copied from another project that uses [the Task task runner tool](https://taskfile.dev/#/) In that project, it is appropriate for the workflow to be triggered on any change to the Task configuration file, and so it was added to the `paths` filter. This project uses npm instead of Task, and does not contain a taskfile, so the presence of that path in the filters …

Remove inappropriate element from paths filters of "Check Packaging" workflow

---

.github/dependabot.yml

The project has a dependency on the `@types/node` package. That package follows the major version of Node.js.
https://stackoverflow.com/questions/42035263/relationship-between-the-version-of-node-js-and-the-version-of-types-node
Since we are now using Node.js 16.x for the development of the project, we must also use the ^16.x series of `@types/node`.
Since there are 17.x versions of the `@types/node` package available, Dependabot would submit unwanted PRs to bump the dependency to those versions (e.g., https://github.com/arduino/setup-task/pull/295). This configuration prevents that. Dependabot will continue to submit PRs for bumps to any new minor or patch releases made within the current major version series.
Since this configuration prevents Dependabot from submitting major version …

Prevent inappropriate `@types/node` bumps from Dependabot

---

package-lock.json
package.json

The `version` field is only needed if the package is to be published. In this project, `package.json` is used only for management of the dependencies and scripts for internal development.
For this reason, having a `version` field in the file is harmful because it increases the effort and complexity of making a release, and also is likely to get out of sync with the true version.
Reference:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#version
> If you don't plan to publish your package, the name and version fields are optional.
---
This was done last year for the `arduino/setup-task` action without any ill effects: https://github.com/arduino/setup-task/pull/49

Remove version field from `package.json`

---

.github/workflows/check-npm.yml

A "Check npm" GitHub Actions workflow is used to check for problems with the repository's npm configuration files.
This workflow is hosted and maintained in a repository dedicated to a collection of such reusable assets.
Several enhancements have been made to the upstream file, but those had not yet been pulled into this repository:
- Correct typo in workflow step name
https://github.com/per1234/.github/commit/8980338b9938b9709c25b8b06c7a9e836f962cbe
- Restrict permissions of `GITHUB_TOKEN`
https://github.com/per1234/.github/commit/110526423b2fb08f0145f604bcc11c3d2ee4fe77
- Install referenced schema
https://github.com/per1234/.github/commit/61d9f9b8e23d17917ffbdfee3fa1b89ecbc673f8

Sync "Check npm" workflow with upstream

---

.github/workflows/check-npm.yml

The "Check npm" GitHub Actions workflow validates the repository's `package.json` npm manifest file against its JSON schema to catch any problems with its data format.
In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The `package.json` schema was recently updated to share resources with the `prettierrc.json` schema, which caused the validation to start failing:
```text
schema /home/runner/work/_temp/json-schema/package-json-schema.json is invalid
error: can't resolve reference https://json.schemastore.org/prettierrc.json from id #
```
The solution is to configure the workflow to download that schema as well and also to provide its path to the avj-cli validator via an `-r` flag.

Install referenced schema in "Check npm" workflow

---

action.yml

The Node.js version for use when executing the action in the GitHub Actions runner is configured via the [`runs.using`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing) field of the [`action.yml` metadata file](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions).
Previously, the action was configured to use **Node.js** 12.x. This was actually the result of an oversight, as **Node.js** 16.x has been used for the development and validation of the action since 2022-01-11 (https://github.com/arduino/arduino-lint-action/pull/42). It will be important to use the same version on the runner as the action is validated for by the project infrastructure in order to ensure the expected behavior.
In addition, [GitHub …

Specify Node.js 16.x runtime for action execution in runner

---

.github/CONTRIBUTING.md
.github/workflows/check-npm.yml
.github/workflows/check-packaging-ncc-typescript-npm.yml
.github/workflows/test.yml
package-lock.json
package.json

The [**actions/setup-node**](https://github.com/actions/setup-node) GitHub Actions action is used to set up **Node.js** in the GitHub Actions runner machine.
The action supports obtaining the Node.js version to set up from the `engines.node` property of the package.json file:
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file
This allows us to define the standardized version of **Node.js** for use by project infrastructure and contributors in a single place rather than having to maintain multiple instances of that data.

Use `engines.node` as source of version data for "actions/setup-node" action

---

package-lock.json
package.json

The major version number of the action's `@types/node` dependency should match the version of Node.js in use.
Node.js was bumped to 20.x (https://github.com/arduino/arduino-lint-action/pull/350), so `@types/node` must also be bumped.

Bump `@types/node` to 20.x

---

.github/workflows/check-npm.yml
.github/workflows/check-packaging-ncc-typescript-npm.yml
.npmrc

This will produce an error if a contributor attempts to run an `npm` command in the project using an unsupported version of **Node.js**.

Configure npm to enforce standard project Node.js version

---

README.md

A 2.0.0 release of the action has been made. To accompany it, a `v2` major version ref has been created. For this reason, in order to use the latest release of the action, the `v2` major version ref must now be used in workflows.
The workflow snippets in the readme are hereby updated to demonstrate the use of this major version ref.

Update snippets in readme to use v2 ref

---

.github/workflows/check-npm-dependencies-task.yml

This GitHub Actions action is used by the "Check Go Dependencies" workflow to install the "Licensed" tool in the runner workspace. At the time the workflow was developed, the action was owned by GitHub user `jonabc`, and so the action was referenced as `jonabc/setup-licensed` in the workflow.
Since that time, the action was transferred to the `github` GitHub organization:
https://github.com/github/setup-licensed
Making things more confusing is the fact that there is now [a development fork](https://github.com/jonabc/setup-licensed) of the `github/setup-licensed` repository under GitHub user `jonabc`'s account, meaning that the redirect GitHub provides from the old to the new repository after a transfer does not exist for this action. This resulted in the workflow referencing an outdated …

Correct "setup-licensed" action ref in dependencies license check workflow

---

.github/workflows/check-npm-dependencies-task.yml

The version of the [**Licensed**](https://github.com/github/licensed) tool for use in the GitHub Actions workflow is defined via the **github/setup-licensed** action's `version` input.
Previously the action was configured to install version 3.x of the action. That version is significantly outdated. The workflow is hereby updated to use the latest version of **Licensed**.

Update Licensed version in dependencies license check workflow

---

.licenses/npm/@fastify/busboy.dep.yml
.licenses/npm/semver-6.3.0.dep.yml

The dependency license metadata is generated by the [**Licensed**](https://github.com/github/licensed) tool. Previous versions of this tool added a trailing space on the `summary` key. Although trailing whitespace in human produced content is not permitted, machine generated content is used as-is, and so these trailing spaces were left in the metadata files.
It seems that the defect in the **Licensed** tool that caused the trailing space was fixed in a recent version because it is now absent in the metadata files produced by the tool. The metadata files are hereby updated to use the format of the version of the **Licensed** tool currently in use.

Remove trailing space from dependency license metadata

---

.github/workflows/check-npm-dependencies-task.yml

This GitHub Actions action is used by the dependency license check workflow to install the [**Licensed**](https://github.com/licensee/licensed) tool in the runner workspace.
The action has a convoluted history of ownership: the repository was originally owned by GitHub user [`jonabc`](https://github.com/jonabc). It was later transferred to the [`github`](https://github.com/github) organization. Then GitHub abandoned the project, archiving the repository. The [`licensee`](https://github.com/licensee) organization has now created a hard fork of the action, which is recommended in [the readme of the `github/setup-licensed` repository](https://github.com/github/setup-licensed#setup-licensed).
The `licensee` organization has also taken over the management of the **Licensed** tool, and their …

Use maintained fork of "setup-licensed" action in dependency license check workflow

---

.github/workflows/check-npm-dependencies-task.yml

The version of the "Licensed" tool for use in the GitHub Actions workflow is defined via the "licensee/setup-licensed" action's `version` input.
The workflow contains two jobs that use the action.
Previously (https://github.com/arduino/arduino-lint-action/pull/465), the action was configured to install the latest version of Licensed in one job, but by accident the update was performed in the other job, leaving it using the significantly outdated version 3.x of the action.
The workflow is hereby updated to use the latest version of Licensed in all jobs.

Bump "Licensed" version in dependency license check workflow
